const CONFIG = {
    titleWeb: "Cậu thích tớ phải không nào?",
    introTitle: 'Helu cậu',
    introDesc: `Tớ có điều này muốn hỏi cậu nhớ phải trả lời thật lòng nhaaa.,
    btnIntro: 'OK',
    title: 'Cậu thích tớ phải không nào?',
    desc: 'Nếu cậu ko trả lời mà thoát ra tức là muốn làm ny tớ rùi đó nha :v ',
    btnYes: 'Thích lắm <33',
    btnNo: 'Không nha :3',
    question: 'Nói cho tớ lí do cậu thích tớ đi :vvvv',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Thích...,
    mess: 'Mình biết mà 🥰',
    messDesc: 'Tối nay 8h, mình qua đón đi chơi nha.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://github.com/zukahai/Confess-Crush' //link mess của các bạn. VD: https://www.facebook.com/messages/t/10001418833353
